### ISSUE TITLE
Sometimes migration starts before the server

### ISSUE THREAD

**Issue by palfrey** [raisenational/serverless-dynamodb#12]
The [`index.js`](https://github.com/raisenational/serverless-dynamodb/blob/d22bc88b61948cda69ac560706637c673d30e340/index.js#L4) has the following code:

```js
            if (!options.noStart) {
              dynamodbLocal.start(options);
            }
            return Promise.resolve()
            .then(() => options.migrate && this.migrateHandler())
            .then(() => options.seed && this.seedHandler());
```

An initial reading of this would go "cool, the DB starts, then we do migrations and seed". Except that's not always quite true. The `.start()` function only spawns the DB, but it's not necessarily started when it returns, especially in slower environments like Github Actions.

And so I periodically get ``UnknownEndpoint: Inaccessible host: `localhost' at port `8000'. This service may not be available in the `localhost' region.`` while trying to make some of the tables, and then it goes and makes the others but doesn't return properly.

Not sure if the "wait for the DB to be talking" should be here or in https://github.com/raisenational/aws-dynamodb-local, but either way it's needed to make this work reliably.

**Comment by domdomegg** [comment]
Thanks for raising this! I agree this shouldn't happen, but agree with your reasoning that on some systems this can happen.

I think the proper solution would be to poll DynamoDB local for when it's available. I feel like this should live in aws-dynamodb-local, and we call it here before running migrations and seeding. This approach seems preferable to me over increasing the general timeout because I think aws-dynamodb-local should be able to better keep track of the process (e.g. not wait on a timeout when we know the process has just crashed).
