### ISSUE TITLE
Migration to async/await left some undefined resolves

### ISSUE THREAD

**Issue by juhana** [raisenational/serverless-dynamodb#23]
0.2.46 throws this error at startup:

> ReferenceError: resolve is not defined  
>    at [..]/node_modules/serverless-dynamodb/index.js:401:21

Looks like there's a couple of `resolve`s left that don't exist anymore after migrating from Promise(resolve) style to async/await:

https://github.com/raisenational/serverless-dynamodb/compare/v0.2.45...v0.2.46#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R401

**Comment by domdomegg** [comment]
Thanks so much for raising this, and for identifying the root cause of the problem!

Sorry for the disruption. I plan in future to convert this project to TypeScript and add better unit tests to catch future bugs like this (#8). I appreciate the annoyance problems in a library like this can cause.

I've raised #26 to fix this, which I'll likely merge and release soon. Would appreciate your review if you have time, and do let me know if the problem remains in the new version.

**Comment by juhana** [comment]
0.2.47 works without issues! Thanks for the quick fix.
